### ISSUE TITLE
Just Appreciation.

### ISSUE THREAD

**Issue by riasat-sheikh** [cormiertyshawn895/PixelPerfect#1]
My eyes are bad and can't read small texts. I need to keep my display settings to show large texts on all three of my devices. It looks ugly for most people but I need to. Most of the iOS apps I am running on macOS has this small font issue. 

Thank you so much for creating this and providing it for free. You can't even imagine how much this is helping me. I can finally read things properly. XD

**Comment by cormiertyshawn895** [comment]
Love it! Many thanks for your kind words, very glad Pixel Perfect is helping you read things more clearly. ❤️
