### ISSUE TITLE
Can you share the wallpaper?

### ISSUE THREAD

**Issue by elonwoo** [cormiertyshawn895/PixelPerfect#10]
https://github.com/cormiertyshawn895/PixelPerfect/blob/main/PixelPerfect/Screenshots/screenshot-animation.gif

I love PixelPerfect App.
I also like the blue wallpaper, can you share it?

Sorry about this issue.

**Comment by cormiertyshawn895** [comment]
Of course! The blue wallpaper is a simple gradient sampled from Mouse and Trackpad videos in System Settings.
![Light Mode](https://github.com/cormiertyshawn895/PixelPerfect/assets/57056759/9f4dd8e0-f1e2-455f-8031-08f53f175c91)
![Dark Mode](https://github.com/cormiertyshawn895/PixelPerfect/assets/57056759/dc863b05-4c75-46b5-9adc-acce13a4c9a7)
