### ISSUE TITLE
App's name

### ISSUE THREAD

**Issue by Fofer** [cormiertyshawn895/PixelPerfect#3]
This is a great app. Thank you so much for making and sharing it!  I really appreciate it.  This is a minor issue but every time I try to rename it from "Pixel Perfect (right click to open)" to just "Pixel Perfect," it reverts right back.  Hmm, I've never seen such behavior before.  As you know we only have to right-click for the first launch. After that, it's no longer necessary.  So just wondering if we can rename it and if not, why not?

Thanks again!

**Comment by cormiertyshawn895** [comment]
This is a limitation on how app name localization works. You can work around this by renaming it into "Pixel Perfect " with a space after "Perfect".

**Comment by Fofer** [comment]
That works, thanks!
