### ISSUE TITLE
Wrong translation when macOS is set to French

### ISSUE THREAD

**Issue by Write** [cormiertyshawn895/PixelPerfect#4]
![Screenshot du 2023-05-21 à 14 50 24](https://github.com/cormiertyshawn895/PixelPerfect/assets/541722/5e4b84ad-9292-4762-979c-50a3d00fc53f)

Hello, seems there's a little issue ^^' it seems to be Finnish ? 

Otherwise, very nice and needed app. Thanks a lot.

**Comment by cormiertyshawn895** [comment]
Thank you for helping us make Pixel Perfect better!

[Pixel Perfect 1.1](https://github.com/cormiertyshawn895/PixelPerfect/releases) fixes this issue. The user interface now appears correctly in French.
