### ISSUE TITLE
Name of the App without " (right click to open)"

### ISSUE THREAD

**Issue by frame** [cormiertyshawn895/PixelPerfect#5]
Would you consider releasing the application without the unquarantine instructions in the localized filename? "Pixel Perfect (right click to open)" -> "Pixel Perfect".

Yes, it's a hassle to launch unsigned apps for the first time, but once it's done the instructions keep showing up when using Launchpad, Raycast or Alfred to launch Pixel Perfect. I understand and respect the intent, but my inner monk still rebels.

Thank you for reading!

**Comment by cormiertyshawn895** [comment]
https://github.com/cormiertyshawn895/PixelPerfect/issues/3

For now, you can work around this by renaming the app into "Pixel Perfect " with a space after "Perfect" to give it a cleaner appearance in Launchpad, Raycast or Alfred.

**Comment by cormiertyshawn895** [comment]
Fixed in the latest release. https://github.com/cormiertyshawn895/PixelPerfect/releases
