### ISSUE TITLE
"Update Available" link re-downloads 1.0, not 1.1

### ISSUE THREAD

**Issue by RicardoPassavantes** [cormiertyshawn895/PixelPerfect#6]
The "update available" link inside of the 1.0 version does not point to the 1.1 download link, but downloads the 1.0 again.

Had to go directly to GitHub to download the updated version.

**Comment by cormiertyshawn895** [comment]
Fixed with https://github.com/cormiertyshawn895/PixelPerfect/commit/5329840143c8988081c99a0278baca7c689cc2d6
